### ISSUE TITLE
Add support for indexes

### ISSUE THREAD

**Issue by greg0ire** [roukmoute/DoctrinePrefixBundle#2]
I added indexes to some of my entities, like this:

``` yml
    indexes:
        admin_entity_created_at_index:
            columns: [ createdAt ]
        admin_entity_library_type_index:
            columns: [ libraryType ]
```

Having them prefixed too would be nice.

**Comment by roukmoute** [comment]
Could you give me a concrete example ?
You have added indexes in a yml file ?

**Comment by greg0ire** [comment]
Exactly! Here is the complete contents of the yml mapping : 


```yml
MedNum\PortalBundle\Entity\AdminEntity:
    type: entity
    table: null
    repositoryClass: MedNum\PortalBundle\Entity\AdminEntityRepository
    fields:
    lifecycleCallbacks: {  }

    manyToMany:
        libraries:
            targetEntity: MedNum\PortalBundle\Entity\Library
            mappedBy: adminEntities

    oneToMany:
        contracts:
            targetEntity: MedNum\PortalBundle\Entity\Contract
            mappedBy: adminEntity

    # create one index per filter in the listing
    indexes:
        # name and manualSlug already have a unique index
        admin_entity_created_at_index:
            columns: [ created_at ]
        admin_entity_library_type_index:
            columns: [ library_type ]
        # fake is a boolean, and indexes on booleans are not worth it

```
