### ISSUE TITLE
[Bug] add prefix to specified bundles 

### ISSUE THREAD

**Issue by aitboudad** [roukmoute/DoctrinePrefixBundle#5]
Hi I want to add prefix to specified bundles only, but I get the following exception:

![selection_001](https://cloud.githubusercontent.com/assets/1753742/5358775/a660caa0-7faf-11e4-9e1f-6c31ad6b8419.png)

Here is my config:

``` yaml
roukmoute_doctrine_prefix:
    prefix:  app
    bundles: ['AppBundle']
    encoding: UTF-8
```
